use-grammars = { only = ["bash", "c", "cpp", "D"] }


[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[language-server.clangd]
args = ["-header-insertion=never"]

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
