#!/usr/bin/env zsh

THEME_ALPHA=e0

THEME_BG="0x${THEME_ALPHA}1f232e"
THEME_FG="0x${THEME_ALPHA}cbcbc6"

THEME_ACCENT="0x${THEME_ALPHA}f6cd76"
THEME_ACCENT_BRIGHT="0x${THEME_ALPHA}"

THEME_BLACK="0x${THEME_ALPHA}191d29"
THEME_RED="0x${THEME_ALPHA}de8778"
THEME_GREEN="0x${THEME_ALPHA}adca7a"
THEME_YELLOW="0x${THEME_ALPHA}f3d187"
THEME_BLUE="0x${THEME_ALPHA}84c8f5"
THEME_MAGENTA="0x${THEME_ALPHA}cbbaf5"
THEME_CYAN="0x${THEME_ALPHA}a2dec7"
THEME_WHITE="0x${THEME_ALPHA}c7c7c7"

THEME_BLACK_BRIGHT="0x${THEME_ALPHA}686868"
THEME_RED_BRIGHT="0x${THEME_ALPHA}e38c7d"
THEME_GREEN_BRIGHT="0x${THEME_ALPHA}c2e48a"
THEME_YELLOW_BRIGHT="0x${THEME_ALPHA}f8d68b"
THEME_BLUE_BRIGHT="0x${THEME_ALPHA}89cdfa"
THEME_MAGENTA_BRIGHT="0x${THEME_ALPHA}d0bffa"
THEME_CYAN_BRIGHT="0x${THEME_ALPHA}a7e3cc"
THEME_WHITE_BRIGHT="0x${THEME_ALPHA}fefefe"
