#!/usr/bin/env bash


log_info() {
  printf "\x1b[36m[info]\x1b[0m: ${1}\n"
}

log_warn() {
  printf "\x1b[33m[warn]\x1b[0m: ${1}\n"
}

log_error() {
  printf "\x1b[31m[error]\x1b[0m: ${1}\n"
}
create_symlink() {
  local src="$1"
  local dest="$2"

  if [[ "$opt_silent" != "true" ]]; then
    log_info "linking \'${src}\' -> \'${dest}\'"
  fi

  if [[ -e "$dest" ]]; then
    if [[ "$opt_force" == "true" ]]; then
      destroy_symlink "$dest"
    else
      if [[ "$opt_silent" != "true" ]]; then
        log_warn "file \'${dest}\' already exists"
      fi

      return
    fi
  fi

  # remove symlink on error
  if ! ln -s "$src" "$dest" &>/dev/null; then
    if [[ "$opt_silent" != "true" ]]; then
      log_error "failed to link \'${src}\' to \'${dest}\'"
    fi

    destroy_symlink "$dest"
    exit 1
  fi
}

destroy_symlink() {
  dest="$1"

  if [[ "$opt_silent" != "true" ]]; then
    log_info "deleting \'${dest}\'"
  fi

  rm -rf "$dest"
}

install_dotfiles() {
  if [[ "$opt_silent" != "true" ]]; then
    log_info "installing dotfiles"
  fi

  # create symlinks for each *.sym file in the repository in the form of
  # ~/.<dotfile>
  for src in $(ls ${dotfile_path}/**/*.sym); do
    dest="${HOME}/.$(basename "${src%.*}")"
    create_symlink "$src" "$dest" 
  done
}

uninstall_dotfiles() {
  if [[ "$opt_silent" != "true" ]]; then
    log_info "uninstalling dotfiles"
  fi

  # deleting createed symlinks for each *.sym file in the repository in the form of
  # ~/.<dotfile>
  for src in $(ls ${dotfile_path}/**/*.sym); do
    dest="${HOME}/.$(basename "${src%.*}")"
    destroy_symlink "$dest"
  done
}
