#!/usr/bin/env bash


log_info() {
  printf "\x1b[36m[info]\x1b[0m: ${1}\n"
}

log_warn() {
  printf "\x1b[33m[warn]\x1b[0m: ${1}\n"
}

log_error() {
  printf "\x1b[31m[error]\x1b[0m: ${1}\n"
}

print_help() {
  printf "Usage: $0 [-f|-h|-s]

Options:
  -f  Force   Forces operations to proceed, ignoring warnings
  -h  Help    Displays this help message
  -s  Silent  Prevents output from being printed\n"
}

destroy_symlink() {
  dest="$1"

  if [[ "$opt_silent" != "true" ]]; then
    log_info "deleting \'${dest}\'"
  fi

  if [[ -d "$dest" ]]; then
    rm -rf "$dest"
  else
    unlink "$dest"
  fi
}

uninstall_dotfiles() {
  if [[ "$opt_silent" != "true" ]]; then
    log_info "uninstalling dotfiles"
  fi

  # deleting createed symlinks for each *.zsh file in the repository in the form of
  # ~/.<dotfile>
  for src in $(ls ${DOTFILE_ROOT}/**/*.zsh ${DOTFILE_ROOT}/**/*.sym); do
    dest="${HOME}/.$(basename "${src%.*}")"
    destroy_symlink "$dest"
  done
}

cd "$(dirname "$0")/.."

DOTFILE_ROOT="$(pwd -P)"

while getopts fhs flag; do
  case "${flag}" in
    f)
      opt_force=true
      ;;
    h)
      print_help
      exit 0
      ;;
    s)
    opt_silent=true
    ;;
    *)
    exit 1
    ;;
    esac
    done

    uninstall_dotfiles
    exit 0
