alias ....="cd ../../.."
alias ...="cd ../.."
alias ..="cd .."
alias gd="open -a Github\ Desktop"
alias img="magick mogrify -monitor -format png *.heic"
alias make="bear -- make"
alias yt="yt-dlp --extract-audio --audio-format mp3"
