alias ....="cd ../../.."
alias ...="cd ../.."
alias ..="cd .."
alias gd="open -a Github\ Desktop"
alias img="magick mogrify -monitor -format png *.heic"
alias make="bear -- make"
alias todo="rg -n -e '(TODO|HACK|FIXME|BUG|NOTE):([ ]*)' | tr -s ' ' | fzf | cut -d ':' -f 1-2 | xargs hx"
alias yt="yt-dlp --extract-audio --audio-format mp3"
